version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  mico-wire-tap-node:
    lang: node
    handler: ./mico-wire-tap-node
    image: zwickel/mico-wire-tap-node:latest
    